---
- name: Install NTP
  yum: name={{ item }} state=latest
  with_items:
  - ntp

- name: Set the correct timezone
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes

- name: Ensure NTP is running and enabled at system start.
  service:
    name: ntpd
    state: started
    enabled: yes

- name: Since chrony can conflict, ensure it is not running and disabled at system start.
  service:
    name: chronyd
    state: stopped
    enabled: no
