---
- name: Ensure /root/bin present
  file:
    path: /root/bin
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy 'check' script
  copy:
    src: check_httpd_and_mysqld
    dest: /root/bin
    owner: root
    group: root
    mode: 0755

- name: Copy 'restart' script
  copy:
    src: restart_httpd_and_mysqld
    dest: /root/bin
    owner: root
    group: root
    mode: 0755

- name: Copy 'track memory' script
  copy:
    src: track_free_memory
    dest: /root/bin
    owner: root
    group: root
    mode: 0755

- name: Copy check_script logrotate config file
  copy:
    src: check_scripts
    dest: /etc/logrotate.d
    owner: root
    group: root
    mode: 0644

- name: "Cron 'check' script"
  cron:
    name: Check if httpd and mysqld are running
    minute: "*/5"
    job: "/root/bin/check_httpd_and_mysqld > /dev/null 2>&1"
  notify:
  - restart crond

- name: "Cron 'track free' script"
  cron:
    name: Track free memory
    minute: "*/5"
    job: "/root/bin/track_free_memory > /dev/null 2>&1"
  notify:
  - restart crond

- name: "Cron 'restart' script"
  cron:
    name: Restart httpd and mysqld (reclaim memory)
    hour: "5"
    minute: "1"
    job: "/root/bin/restart_httpd_and_mysqld > /dev/null 2>&1"
  notify:
  - restart crond
