# An encrypted vault.yml file must be created in this directory with exact same structure as below except with
# node names vault_linux (instead of simply "linux") and vault_db (instead of simply "db") and with actual
# values for each of the listed keys like root_user, root_password, wp_name, etc.

linux:
  root_user: "{{ vault_linux.root_user }}"
  root_password: "{{ vault_linux.root_password }}"
  deploy_user: "{{ vault_linux.deploy_user }}"
  deploy_password: "{{ vault_linux.deploy_password }}"
  ssh_port: "{{ vault_linux.ssh_port }}"

db:
  root_password: "{{ vault_db.root_password }}"
  wp_user: "wp_user"
  wp_password: "{{ vault_db.wp_password }}"

webserver:
  user: "apache"
  group: "apache"
  root_directory: "/var/www"

# Set up for machine access from ansible
ansible_user: "{{ linux.deploy_user }}"
ansible_password: "{{ linux.deploy_password }}"
ansible_port: "{{ linux.ssh_port }}"
ansible_sudo_pass: "{{ linux.deploy_password }}"
ansible_ssh_pass: "{{ linux.deploy_password }}"
