---
- name: Add EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/7/x86_64/
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes

- name: Add Remi-72 repo
  yum_repository:
    name: Remi-72
    description: Remi-72 YUM repo
    baseurl: http://rpms.remirepo.net/enterprise/7/php72/x86_64/
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes

- name: Install PHP 7.2
  yum: name={{ item }} state=latest
  with_items:
  - php
  - php-cli
  - php-mysqlnd  # To run MySQL 5.7 (not 5.6), need "nd" version (native driver)
  - php-fpm
  - php-xml  # Needed by backwpup
  notify: restart php-fpm

- name: Increase max file upload size
  lineinfile:
    path: /etc/php.ini
    regexp: 'upload_max_filesize'
    line: 'upload_max_filesize = 64M'
  notify: restart php-fpm

- name: Increase memory limit (to allow for max file upload size)
  lineinfile:
    path: /etc/php.ini
    regexp: 'memory_limit'
    line: 'memory_limit = 64M'
  notify: restart php-fpm

- name: Increase max post size (to allow for max file upload size)
  lineinfile:
    path: /etc/php.ini
    regexp: 'post_max_size'
    line: 'post_max_size = 64M'
  notify: restart php-fpm

- name: Increase PHP execution time (to allow for max file upload size)
  lineinfile:
    path: /etc/php.ini
    regexp: 'max_execution_time'
    line: 'max_execution_time = 300'
  notify: restart php-fpm
